apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  labels:
    app: frontend

spec:
  updateStrategy:
#    type: RollingUpdate
    type: OnDelete
#    rollingUpdate:
#      maxUnavailable: 2
  template:
    metadata:
      name: my-pod-webserver
      labels: 
        apps: my-app
        tier: frontend
    spec:
      containers:
        - name: my-container-nginx
          image: tomcat
#      nodeName: kind-worker3 // atibuição direta
#     nodeSelector:
#       disktype: ssd  //atribuição por labels

  selector:
    matchLabels:
      apps: my-app
