apiVersion: v1
kind: Pod

metadata:
  name: specific-node-pod
  labels:
    apps: my-app
    tier: frontend
    
spec:
  containers:
    - name: redis
      image: redis
  nodeSelector:
    disktype: ssd
#  nodeName: kind-worker3 // atribuição direta ao node